cancervariants/disease-normalization

- .gitignore
- LICENSE
- Pipfile
- disease/__init__.py
- disease/__version__.py
- disease/database.py
- disease/etl/merge.py
- disease/main.py
- disease/query.py
- disease/schemas.py
- setup.cfg
- setup.py
- tests/conftest.py
- tests/unit/data/diseases.json
- tests/unit/test_database.py
- tests/unit/test_merge.py
- tests/unit/test_query.py
> Issue 12 gh

- .gitignore
- README.md
- disease/cli.py
- disease/database.py
- disease/etl/ncit.py
> Fix bug in ncit download and default db endpoint 

- README.md
- disease/__init__.py
- disease/database.py
- disease/etl/__init__.py
- disease/etl/base.py
- disease/etl/merge.py
- disease/etl/ncit.py
- disease/etl/omim.py
- disease/etl/oncotree.py
- disease/main.py
- disease/query.py
- disease/schemas.py
- tests/conftest.py
- tests/unit/data/diseases.json
- tests/unit/data/metadata.json
- tests/unit/test_database.py
- tests/unit/test_do.py
- tests/unit/test_merge.py
- tests/unit/test_mondo.py
- tests/unit/test_ncit.py
- tests/unit/test_omim.py
- tests/unit/test_oncotree.py
- tests/unit/test_query.py
Covers several issues because I got locked out of github oops
* Close #11 
* Close #16 
* Handles some VOD correctness stuff (id name, escaping chars correctly)
> Vod id chars

- dynamodb_revisions/README.md
- dynamodb_revisions/add_omim_other_ids.py
I *think* I did the filtering right for the scans but if you think there's a better way, feel free to indicate it
> Initial draft of DB updates

- disease/__init__.py
- disease/query.py
- setup.cfg
> Fix search on partial sources loaded bug

- .github/workflows/github-actions.yml
Also clean up style, Python versions, break out test vs lint
> ci: update gh actions versioning

- disease/cli.py
> fix: click echo msg

- disease/etl/mondo.py
- disease/version.py
> fix: Catch ValueError during MONDO ETL (staging)

- disease/etl/mondo.py
- disease/version.py
> fix: MONDO latest version retrieval

- disease/etl/mondo.py
- disease/version.py
> fix: MONDO latest version retrieval (staging)

- disease/__init__.py
- disease/cli.py
- disease/etl/base.py
- disease/etl/ncit.py
- disease/etl/omim.py
- disease/etl/utils.py
- disease/version.py
- setup.cfg
- tests/unit/data/metadata.json
- tests/unit/test_mondo.py
- tests/unit/test_ncit.py
- tests/unit/test_omim.py
> fix: resolve the ETL problems of the week

- .github/workflows/checks.yml
building off of comment in #121
> ci: test in 3.11

- disease/etl/base.py
- disease/main.py
- tests/unit/test_query.py
> fix: remove therapy references

- disease/etl/base.py
- disease/main.py
- tests/unit/test_query.py
> fix: remove therapy refs

- README.md
- disease/cli.py
- setup.cfg
> fix!: use better name for CLI source option

- disease/database/dynamodb.py
- tests/unit/test_database.py
> feat: optionally define dynamo table names via env variable

- .github/workflows/checks.yml
- .pre-commit-config.yaml
- pyproject.toml
- src/disease/__init__.py
- src/disease/cli.py
- src/disease/database/database.py
- src/disease/database/dynamodb.py
- src/disease/database/postgresql.py
- src/disease/etl/base.py
- src/disease/etl/do.py
- src/disease/etl/mondo.py
- src/disease/etl/ncit.py
- src/disease/etl/oncotree.py
- src/disease/main.py
- src/disease/query.py
- src/disease/schemas.py
- tests/unit/test_mondo.py
this will let me cross out a row on my "PRs to make for every normalizer" spreadsheet
> cicd: use ruff for formatting

- .pre-commit-config.yaml
- Pipfile
- README.md
- pyproject.toml
- src/disease/__init__.py
- src/disease/database/__init__.py
- src/disease/etl/__init__.py
- tests/conftest.py
Fixing similar mistakes/doing similar cleanup as https://github.com/cancervariants/therapy-normalization/pull/388
> style: fix ruff settings

- docs/source/conf.py
- pyproject.toml
- src/disease/__init__.py
- src/disease/query.py
- src/disease/schemas.py
- src/disease/version.py
- tests/unit/test_query.py
* use setuptools-scm for versioning instead of explicit declaration in version.py
* provide version in package root instead of version module
> feat!: use setuptools-scm, capture version at package root

- src/disease/etl/do.py
- src/disease/etl/mondo.py
- src/disease/schemas.py
- tests/data/do/do_20240731.owl
- tests/data/omim/omim_20240806.tsv
- tests/unit/test_merge.py
- tests/unit/test_omim.py
- tests/unit/test_query.py
close #180 
Per material linked there, OMIM's preferred prefix for all terms (OMIM and OMIM phenotypic series) is `MIM`
> fix: update preferred OMIM prefix

- src/disease/database/postgresql.py
- src/disease/database/postgresql/create_record_lookup_view.sql
- src/disease/database/postgresql/create_tables.sql
- src/disease/database/postgresql/delete_normalized_concepts.sql
- src/disease/etl/base.py
- src/disease/etl/merge.py
- src/disease/etl/mondo.py
- src/disease/etl/oncotree.py
- src/disease/query.py
- src/disease/schemas.py
- tests/conftest.py
- tests/unit/test_merge.py
- tests/unit/test_mondo.py
- tests/unit/test_omim.py
- tests/unit/test_oncotree.py
- tests/unit/test_query.py
> feat: add oncologic disease parameter from mondo terms

- .github/workflows/checks.yaml
- pyproject.toml
We use 'tests' in our other projects but I must've slipped on this one
> build: fix test group name

- .github/workflows/checks.yaml
- pyproject.toml
- src/disease/database/postgresql.py
- src/disease/query.py
* https://github.com/GenomicMedLab/software-templates/pull/66
> build!: require python >=3.11

- .github/workflows/checks.yaml
- .pre-commit-config.yaml
* https://github.com/GenomicMedLab/software-templates/pull/60
* https://github.com/GenomicMedLab/software-templates/pull/61
* https://github.com/GenomicMedLab/software-templates/pull/70
> cicd: update precommit

- src/disease/query.py
- src/disease/schemas.py
- tests/unit/test_query.py
> fix!: `xrefs` should have `exactMatch` for `ConceptMapping.relation`

- .pre-commit-config.yaml
- pyproject.toml
- src/disease/cli.py
- src/disease/database/dynamodb.py
- src/disease/database/postgresql.py
- src/disease/etl/__init__.py
- src/disease/etl/merge.py
- src/disease/query.py
- tests/conftest.py
per https://github.com/GenomicMedLab/software-templates/releases/tag/2025.01.08
> style: update ruff

- docs/source/conf.py
- docs/source/managing_data/loading_and_updating_data.rst
- docs/source/managing_data/postgresql.rst
- docs/source/reference/api/etl/disease.etl.update.rst
- docs/source/reference/index.rst
- pyproject.toml
- src/disease/cli.py
- src/disease/etl/__init__.py
- src/disease/etl/base.py
- src/disease/etl/update.py
- src/disease/logs.py
* implement https://github.com/GenomicMedLab/software-templates/pull/83
* update docs
> feat!: overhaul CLI

- pyproject.toml
* incorporate wags-tails fix for NCIt version lookup
* unrestrict owlready version for setuptools compatibility
> build: update dependencies

- src/disease/cli.py
Forgot to add this in previous PR
> feat: add --version to cli

- README.md
- docs/source/index.rst
- docs/source/usage.rst
- pyproject.toml
- src/disease/query.py
- src/disease/schemas.py
- tests/unit/test_api.py
- tests/unit/test_query.py
close #235
* Also introduces deepdiff to simplify equality check in tests
> feat!: use VRS 2.0.1 models

- src/disease/etl/merge.py
- src/disease/query.py
Added some small notes as I re-read through how everything worked
> docs: update notes on how stuff works

- src/disease/cli.py
- src/disease/utils.py
- tests/conftest.py
- tests/unit/test_utils.py
> feat: make mappings dump
